import Head from 'next/head';
import React from 'react';

const Login = () => {
    return (
        <div>
            <Head>
                <title>Login | Shortgun</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main style={{ height: '100vh' }} className='bg-primary d-flex justify-content-center align-items-center'>
                <div className="card">
                    <form className='card-body'>
                        <div class="mb-3">
                            <input type="email" placeholder='Email Address' class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" />
                            <div id="emailHelp" class="form-text">We&apos;ll never share your email with anyone else.</div>
                        </div>
                        <div class="mb-3">
                            <input type="password" placeholder='Password' class="form-control" id="exampleInputPassword1" />
                        </div>
                        <div class="mb-3 form-check">
                            <input type="checkbox" class="form-check-input" id="exampleCheck1" />
                            <label class="form-check-label" for="exampleCheck1">Check me out</label>
                        </div>
                        <button type="submit" class="btn btn-primary w-100">Sign in</button>
                    </form>
                </div>
            </main>
        </div>
    );
};

export default Login;